name: Android Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0

    - name: Create minimal Android project structure
      run: |
        mkdir -p app/src/main
        mv res app/src/main/res
        touch app/build.gradle
        echo "apply plugin: 'com.android.application'" >> app/build.gradle
        echo "android { compileSdkVersion 34 }" >> app/build.gradle

    - name: Run Lint
      run: ./gradlew lint

    - name: Upload Lint Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: lint-reports
        path: app/build/reports/lint-results.xml
